"""SQLModel table definitions aligned with SPEC section 4."""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Index, Integer, String, Table, Text, func, text
from sqlalchemy.dialects import postgresql
from sqlmodel import Field, SQLModel

from app.db.types import GUID, JSONB


def uuid_pk() -> Column:
    """Return a UUID primary-key column generated by the application."""

    return Column(GUID(), primary_key=True, default=uuid.uuid4)


def created_at_column() -> Column:
    """Return a timestamp column with the SPEC default."""

    return Column(DateTime(timezone=True), server_default=func.now())


class User(SQLModel, table=True):
    """`users` table."""

    __tablename__ = "users"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    username: str = Field(sa_column=Column(String(64), unique=True, nullable=False))
    password_hash: str = Field(sa_column=Column(Text, nullable=False))
    role: str = Field(sa_column=Column(String(16), nullable=False))
    display_name: Optional[str] = Field(default=None, sa_column=Column(String(64)))
    avatar: Optional[str] = Field(default=None, sa_column=Column(String(32)))
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class Class(SQLModel, table=True):
    """`classes` table."""

    __tablename__ = "classes"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    name: str = Field(sa_column=Column(String(64), nullable=False))
    teacher_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("users.id")),
    )
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class ClassMember(SQLModel, table=True):
    """`class_members` table."""

    __tablename__ = "class_members"

    class_id: uuid.UUID = Field(
        sa_column=Column(
            GUID(),
            ForeignKey("classes.id"),
            primary_key=True,
        )
    )
    student_id: uuid.UUID = Field(
        sa_column=Column(
            GUID(),
            ForeignKey("users.id"),
            primary_key=True,
        )
    )


class Assignment(SQLModel, table=True):
    """`assignments` table."""

    __tablename__ = "assignments"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    class_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("classes.id")),
    )
    title: str = Field(sa_column=Column(String(128), nullable=False))
    description: Optional[str] = Field(default=None, sa_column=Column(Text))
    template_code: Optional[str] = Field(default=None, sa_column=Column(Text))
    due_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime(timezone=True)))
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class Submission(SQLModel, table=True):
    """`submissions` table."""

    __tablename__ = "submissions"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    assignment_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("assignments.id")),
    )
    student_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("users.id")),
    )
    code: str = Field(sa_column=Column(Text, nullable=False))
    blockly_xml: Optional[str] = Field(default=None, sa_column=Column(Text))
    language: Optional[str] = Field(
        default="python",
        sa_column=Column(String(16), server_default=text("'python'")),
    )
    submitted_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), server_default=func.now()),
    )
    status: Optional[str] = Field(
        default="submitted",
        sa_column=Column(String(16), server_default=text("'submitted'")),
    )


class Experiment(SQLModel, table=True):
    """`experiments` table."""

    __tablename__ = "experiments"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    user_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("users.id")),
    )
    class_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("classes.id")),
    )
    assignment_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("assignments.id")),
    )
    code_snapshot: Optional[str] = Field(default=None, sa_column=Column(Text))
    source: str = Field(sa_column=Column(String(16), nullable=False))
    action: Optional[str] = Field(default=None, sa_column=Column(String(32)))
    strategy_params: Optional[dict] = Field(
        default=None,
        sa_column=Column(JSONB()),
    )
    started_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime(timezone=True)))
    ended_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime(timezone=True)))
    telemetry_blob_url: Optional[str] = Field(default=None, sa_column=Column(Text))
    summary: Optional[dict] = Field(default=None, sa_column=Column(JSONB()))


telemetry_table = Table(
    "telemetry",
    SQLModel.metadata,
    Column("experiment_id", GUID(), nullable=False),
    Column("ts", DateTime(timezone=True), nullable=False),
    Column("source", String(16)),
    Column("imu", JSONB()),
    Column("joints", JSONB()),
    Column("motors", JSONB()),
    Column("step_count", Integer),
    Column("battery", postgresql.REAL),
    Column("assist_mode", String(32)),
    Index("ix_telemetry_experiment_id_ts", "experiment_id", text("ts DESC")),
)


class Device(SQLModel, table=True):
    """`devices` table."""

    __tablename__ = "devices"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    name: Optional[str] = Field(default=None, sa_column=Column(String(64)))
    pi_host: Optional[str] = Field(default=None, sa_column=Column(String(128)))
    pi_user: Optional[str] = Field(default=None, sa_column=Column(String(32)))
    ssh_key_ref: Optional[str] = Field(default=None, sa_column=Column(String(128)))
    online: Optional[bool] = Field(default=False, sa_column=Column(Boolean, server_default=text("FALSE")))
    current_deployment_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID()),
    )
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class Deployment(SQLModel, table=True):
    """`deployments` table."""

    __tablename__ = "deployments"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    submission_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("submissions.id")),
    )
    device_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("devices.id")),
    )
    approved_by: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("users.id")),
    )
    version: Optional[int] = Field(default=None, sa_column=Column(Integer))
    status: Optional[str] = Field(default=None, sa_column=Column(String(16)))
    started_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime(timezone=True)))
    ended_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime(timezone=True)))
    log_blob_url: Optional[str] = Field(default=None, sa_column=Column(Text))


class ClassifierDataset(SQLModel, table=True):
    """`classifier_datasets` table."""

    __tablename__ = "classifier_datasets"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    owner_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("users.id")),
    )
    name: Optional[str] = Field(default=None, sa_column=Column(String(64)))
    samples: Optional[dict] = Field(default=None, sa_column=Column(JSONB()))
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class ClassifierModel(SQLModel, table=True):
    """`classifier_models` table."""

    __tablename__ = "classifier_models"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    dataset_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("classifier_datasets.id")),
    )
    algorithm: Optional[str] = Field(default=None, sa_column=Column(String(32)))
    metrics: Optional[dict] = Field(default=None, sa_column=Column(JSONB()))
    model_blob_url: Optional[str] = Field(default=None, sa_column=Column(Text))
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class LlmSession(SQLModel, table=True):
    """`llm_sessions` table."""

    __tablename__ = "llm_sessions"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    user_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(GUID(), ForeignKey("users.id")),
    )
    messages: Optional[dict] = Field(default=None, sa_column=Column(JSONB()))
    context: Optional[dict] = Field(default=None, sa_column=Column(JSONB()))
    created_at: Optional[datetime] = Field(default=None, sa_column=created_at_column())


class AuditLog(SQLModel, table=True):
    """`audit_logs` table."""

    __tablename__ = "audit_logs"

    id: uuid.UUID = Field(sa_column=uuid_pk())
    user_id: Optional[uuid.UUID] = Field(default=None, sa_column=Column(GUID()))
    action: Optional[str] = Field(default=None, sa_column=Column(String(64)))
    target: Optional[str] = Field(default=None, sa_column=Column(String(64)))
    payload: Optional[dict] = Field(default=None, sa_column=Column(JSONB()))
    ts: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), server_default=func.now()),
    )
